apiVersion: v1
kind: ConfigMap
metadata:
  name: report-srv-config
  namespace: optimus-uat
  labels:
    app: reportsrv
data:
  application.yml: |+

    logging:
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p ${PID:- } --- [%t] %-40.40logger{39} : %X{RID} %X{CID} - %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}"
      level:
        com.opus.optimus: DEBUG
      file.path: /var/log/optimus
    ##

    server:
      address: 0.0.0.0
      port: 8035
      servlet:
        context-path: /report-server
      tomcat:
        accesslog:
          enabled: true
          prefix: access-log
          suffix: .log
          pattern: '%h %{X-Forwarded-For}i %t %r %s %b %D %p'


    ##

    spring:
      main.allow-circular-references: true
      mvc:
        pathmatch:
          matching-strategy: ant_path_matcher
      cloud.kubernetes.config:
        name: report-server
      application:
        name: report-server
      data:
        mongodb:
          uri: mongodb://${mongodb.cosmos.username}:${mongodb.cosmos.password}@${mongodb.cosmos.host}:${mongodb.cosmos.port}/default?ssl=false&authSource=admin      
      autoconfigure:
        exclude:
          - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
          - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration

    pattern:
      name: '[a-zA-Z0-9-_]+'

    jwt:
      secretKey: ${jwt.secretKey}
      notAfterInMins: 30
      expiryInMins: 15

    azure:
      jwksUrl: ${azurejwks-url}

    refToken:
        key: ${refToken.key}
        iV: 1234567890ABCDEF

    authToken:
        key: ${refToken.key}
        iV: 1234567890ABCDEF


    multi-tenant:
      enabled: true
      repositoryBasePackage: com.opus.optimus
      common:
        dbConnection:
          uri: mongodb://${mongodb.cosmos.username}:${mongodb.cosmos.password}@${mongodb.cosmos.host}:${mongodb.cosmos.port}/common?ssl=false&authSource=admin
      tenants:
        dbConnections:
          optimus:
            uri: mongodb://${mongodb.cosmos.username}:${mongodb.cosmos.password}@${mongodb.cosmos.host}:${mongodb.cosmos.port}/optimus?ssl=false&authSource=admin
          firstData:
            uri: mongodb://${mongodb.cosmos.username}:${mongodb.cosmos.password}@${mongodb.cosmos.host}:${mongodb.cosmos.port}/firstData?ssl=false&authSource=admin
          tmobile:
            uri: mongodb://${mongodb.cosmos.username}:${mongodb.cosmos.password}@${mongodb.cosmos.host}:${mongodb.cosmos.port}/tmobile?ssl=false&authSource=admin
          optimusfin:
            uri: mongodb://${mongodb.cosmos.username}:${mongodb.cosmos.password}@${mongodb.cosmos.host}:${mongodb.cosmos.port}/optimusfin?ssl=false&authSource=admin
          testautomation:
            uri: mongodb://${mongodb.cosmos.username}:${mongodb.cosmos.password}@${mongodb.cosmos.host}:${mongodb.cosmos.port}/testautomation?ssl=false&authSource=admin
          transactive:
            uri: mongodb://${mongodb.cosmos.username}:${mongodb.cosmos.password}@${mongodb.cosmos.host}:${mongodb.cosmos.port}/transactive?ssl=false&authSource=admin

    report:
      tagCollectionName: TagSummaryReport
      errorLogcollectionName: ErrorLog
      tagSummaryMandatoryFilters: createdDate,transactionDate
    download:
      recordFetchLimit: 200000
      maxDuration : 1 Weeks
      maxDurationReportWizardSummary : 2 Months
      maxDurationSummary : 1 Months
      directory : /temp

    caseUrls:
      create-batch: "http://${CASEMGMT_SERVICE_SERVICE_HOST}:80/case/batch"
      add-case: "http://${CASEMGMT_SERVICE_SERVICE_HOST}:80/case/issues"
      process-batch: "http://${CASEMGMT_SERVICE_SERVICE_HOST}:80/case/batch/%s"

    displaySettings:
      dateFormat:
        date: yyyy/MM/dd
        monthAndYear: yyyy/MM
        year: yyyy
        dateAndTime:  yyyy/MM/dd HH:mm:ss
        dayAndMonth:  MM/dd

    app:
      baseUrl:
        http://report-service:80/report-server

    openapi:
      service:
        version: 1.0.0
        title: Report Service API
    skipRequests: /swagger-ui, /v3/api-docs
    reportToServiceMap:
      GLSummaryReport: GLReportService

