apiVersion: apps/v1
kind: Deployment
metadata:
 name: configsrv
 namespace: optimus-qa
 labels:
  app: configsrv
spec:
 selector:
  matchLabels:
   app: configsrv
 replicas: 1
 template:
  metadata:
   labels:
    app: configsrv
  spec:
   volumes:
    - name: configsrv-volume
      configMap:
        name: configsrv-config
        items:
        - key: application.yml
          path: application.yml
    - name: optimus-config-server-develop
      hostPath:
       path: /opt/optimus/configsrv_dev
    - name: optimus-config-server-develop-logs
      hostPath:
       path: /var/log/optimus/configsrv_dev
   containers:
    - name: config-mgt-server
      image: optimusacr.azurecr.io/configuration-server:2.17.0
      imagePullPolicy: IfNotPresent
      env:
       - name: mongodb.cosmos.host
         valueFrom:
          configMapKeyRef:
           name: mongodbcosmos
           key: mongodb.cosmos.host
       - name: mongodb.cosmos.port
         valueFrom:
          configMapKeyRef:
           name: mongodbcosmos
           key: mongodb.cosmos.port
       - name: azurejwks-url
         valueFrom:
          configMapKeyRef:
           name: optimus
           key: azurejwks-url
       - name: mongodb.cosmos.username
         valueFrom:
          secretKeyRef:
           name: mongodbcosmos
           key: mongodb.cosmos.username
       - name: mongodb.cosmos.password
         valueFrom:
          secretKeyRef:
           name: mongodbcosmos
           key: mongodb.cosmos.password
       - name: jwt.secretKey
         valueFrom:
          secretKeyRef:
           name: token
           key: jwt.secretKey
       - name: refToken.key
         valueFrom:
          secretKeyRef:
           name: token
           key: refToken.key
      volumeMounts:
       - name: configsrv-volume
         mountPath: /tmp/conf
       - name: optimus-config-server-develop
         mountPath: /opt/optimus
       - name: optimus-config-server-develop-logs
         mountPath: /var/log/optimus
      ports:
       - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
   name: config-service
   namespace: optimus-qa
   labels:
    app: configsrv
spec:
   selector:
    app: configsrv
   ports:
    - protocol: TCP
      port: 80
      targetPort: 8082

