optimus:
  mongo:
    tenantProperties:
      common:
        uri: mongodb+srv://${mongodb.cosmos.username}:${mongodb.cosmos.password}@${mongodb.cosmos.host}/common?ssl=true&authSource=admin&retrywrites=false
        database: common
      optimus:
        uri: mongodb+srv://${mongodb.cosmos.username}:${mongodb.cosmos.password}@${mongodb.cosmos.host}/optimus?ssl=true&authSource=admin&retrywrites=false
        database: optimus
      firstData:
        uri: mongodb+srv://${mongodb.cosmos.username}:${mongodb.cosmos.password}@${mongodb.cosmos.host}/firstData?ssl=true&authSource=admin&retrywrites=false
        database: firstData
      tmobile:
        uri: mongodb+srv://${mongodb.cosmos.username}:${mongodb.cosmos.password}@${mongodb.cosmos.host}/tmobile?ssl=true&authSource=admin&retrywrites=false
        database: tmobile


caseUrls:
  create-batch: http://${CASEMGMT_SERVICE_SERVICE_HOST}:80/case/batch
  add-case: http://${CASEMGMT_SERVICE_SERVICE_HOST}:80/case/issues
  process-batch: http://${CASEMGMT_SERVICE_SERVICE_HOST}:80/case/batch/%s
  get-case-template: http://${CASEMGMT_SERVICE_SERVICE_HOST}:80/case/casetemplate/internal/%s
  
statusUpdate:     
  batchSize : 5

