apiVersion: apps/v1
kind: Deployment
metadata:
 name: schedular
 namespace: optimus-qa
 labels:
  app: schedular
spec:
 selector:
  matchLabels:
   app: schedular
 replicas: 1
 template:
  metadata:
   labels:
    app: schedular
  spec:
   volumes:
    - name: schedular-volume
      configMap:
        name: schedular-config
        items:
        - key: application.yml
          path: application.yml
    - name: optimus-schedular-develop
      hostPath:
       path: /opt/optimus/schedular_dev
    - name: optimus-schedular-develop-logs
      hostPath:
       path: /var/log/optimus/schedular_dev
    - name: optimus-share
      hostPath:
       path: /opts3
   containers:
    - name: schedular-server
      image: optimusacr.azurecr.io/toolset-scheduler:2.17.0
      imagePullPolicy: IfNotPresent
      env:
       - name: mongodb.cosmos.host
         valueFrom:
          configMapKeyRef:
           name: mongodbcosmos
           key: mongodb.cosmos.host
       - name: mongodb.cosmos.port
         valueFrom:
          configMapKeyRef:
           name: mongodbcosmos
           key: mongodb.cosmos.port
       - name: azurejwks-url
         valueFrom:
          configMapKeyRef:
           name: optimus
           key: azurejwks-url
       - name: mongodb.cosmos.username
         valueFrom:
          secretKeyRef:
           name: mongodbcosmos
           key: mongodb.cosmos.username
       - name: mongodb.cosmos.password
         valueFrom:
          secretKeyRef:
           name: mongodbcosmos
           key: mongodb.cosmos.password
       - name: jwt.secretKey
         valueFrom:
          secretKeyRef:
           name: token
           key: jwt.secretKey
       - name: refToken.key
         valueFrom:
          secretKeyRef:
           name: token
           key: refToken.key
      volumeMounts:
       - name: schedular-volume
         mountPath: /tmp/conf
       - name: optimus-schedular-develop
         mountPath: /opt/optimus
       - name: optimus-schedular-develop-logs
         mountPath: /var/log/optimus
       - name: optimus-share
         mountPath: /opts3
      ports:
       - containerPort: 8285

---

apiVersion: v1
kind: Service
metadata:
   name: scheduler-service
   namespace: optimus-qa
   labels:
    app: schedular
spec:
   selector:
    app: schedular
   ports:
    - protocol: TCP
      port: 80
      targetPort: 8285

