
apiVersion: apps/v1
kind: Deployment
metadata:
 name: audit-srv
 namespace: optimus-qa
 labels:
  app: audit-srv
spec:
 selector:
  matchLabels:
   app: audit-srv
 replicas: 1
 revisionHistoryLimit: 5
 template:
  metadata:
   labels:
    app: audit-srv
  spec:
   volumes:
    - name: audit-srv-config-volume
      configMap:
        name: audit-srv-config
        items:
        - key: application.yml
          path: application.yml
    - name: optimus-audit-server
      hostPath:
       path: /opt/optimus/audit_srv
    - name: optimus-audit-develop-logs
      hostPath:
       path: /var/log/optimus/audit-srv
   containers:
    - name: audit-server
      image: optimusacr.azurecr.io/audit-server:2.17.0
      imagePullPolicy: IfNotPresent
      env:
       - name: mongodb.cosmos.host
         valueFrom:
          configMapKeyRef:
           name: mongodbcosmos
           key: mongodb.cosmos.host
       - name: mongodb.cosmos.port
         valueFrom:
          configMapKeyRef:
           name: mongodbcosmos
           key: mongodb.cosmos.port
       - name: azurejwks-url
         valueFrom:
          configMapKeyRef:
           name: optimus
           key: azurejwks-url
       - name: mongodb.cosmos.username
         valueFrom:
          secretKeyRef:
           name: mongodbcosmos
           key: mongodb.cosmos.username
       - name: mongodb.cosmos.password
         valueFrom:
          secretKeyRef:
           name: mongodbcosmos
           key: mongodb.cosmos.password
       - name: jwt.secretKey
         valueFrom:
          secretKeyRef:
           name: token
           key: jwt.secretKey
       - name: refToken.key
         valueFrom:
          secretKeyRef:
           name: token
           key: refToken.key
      volumeMounts:
       - name: audit-srv-config-volume
         mountPath: /tmp/conf
       - name: optimus-audit-server
         mountPath: /opt/optimus/audit_srv
       - name: optimus-audit-develop-logs
         mountPath: /var/log/optimus
      ports:
       - containerPort: 8287

---

apiVersion: v1
kind: Service
metadata:
   name: audit-service
   namespace: optimus-qa
   labels:
    app: audit-srv
spec:
   selector:
    app: audit-srv
   ports:
    - protocol: TCP
      port: 80
      targetPort: 8287

