apiVersion: apps/v1
kind: Deployment
metadata:
 name: ui
 namespace: optimus-qa
 labels:
  app: ui
spec:
 selector:
  matchLabels:
   app: ui
 replicas: 1
 revisionHistoryLimit: 5
 template:
  metadata:
   labels:
    app: ui
  spec:
   volumes:
    - name: ui
      hostPath:
       path: /opt/optimus/ui-dev
    - name: ui-develop-logs
      hostPath:
       path: /var/log/optimus/ui-dev
   containers:
    - name: ui-server
      image: optimusacr.azurecr.io/ui:2.17.0-1
      imagePullPolicy: IfNotPresent
      volumeMounts:
       - name: ui
         mountPath: /opt/optimus
       - name: ui-develop-logs
         mountPath: /var/log/optimus
      ports:
       - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
   name: ui-service
   namespace: optimus-qa
   labels:
    app: ui
spec:
   selector:
    app: ui
   ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

